version: 0.2

phases:
  install:
    commands:
      - echo "Downloading and installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version  # Verify Terraform installation

  pre_build:
    commands:
      - echo "Terraform execution started on `date`"
      - echo "Current working directory $(pwd)"
      - ls -la

  build:
    commands:
      - echo "Copying frontend backend configuration"
      - cp $ENV_DIR/backend.tf .
      - ls
      - terraform init
      - aws sts get-caller-identity

      - terraform plan -var-file=$ENV_DIR/terraform.tfvars -out=tfplan

      - echo "Contents of current directory:"
      - ls -la

artifacts:
  files:
    - $ENV_DIR/**/*
  name: terraform-plan-output
