version: 0.2

phases:
  install:
    commands:
      - echo "Downloading and installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version  # Verify Terraform installation

  pre_build:
    commands:
      - echo "Terraform execution started on `date`"
      - echo "Current working directory $(pwd)"
      - ls -la
      - echo "Setting up environment..."
      - export TF_VAR_region=$AWS_DEFAULT_REGION
      #- export TF_VAR_lambda_package_path="lambda_package.zip"
      #- echo "Packaging Lambda function..."
      #- cd lambda
      #- npm install  # Install Node.js dependencies if any
      #- zip -r ../modules/lambda/lambda_package.zip .  # Create zip package in the correct directory
      #- cd ..
      #- ls -la
      #- zip -r lambda_fucntion.zip lambda 
      #- cd ..
      #- echo "Lambda function packaging completed."

  build:
    commands:
      - ls -la
      - echo "Copying backend configuration"
      - cp $ENV_DIR/backend.tf .
      - ls
      - cat backend.tf
      - terraform init
      - terraform plan -var-file=$ENV_DIR/terraform.tfvars -out=tfplan
      - echo "Contents of current directory:"
      - ls -la

artifacts:
  files:
    - $ENV_DIR/**/*
  name: terraform-plan-output

# cache:
#   paths:
#     - 'lambda/node_modules/**/*'
